/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Src;

import Src.CustomWidgets.BackgroundMenuBar;
import Src.CustomWidgets.ComponentResizer;
import Src.CustomWidgets.FrameDragListener;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JSeparator;
import javax.swing.UIManager;

/**
 *
 * @author cleber
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateUniserveFrame
     */
    public MainFrame() {
        initComponents();
        
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        maximized = true;
        
        FrameDragListener frameDragListener = new FrameDragListener(this);
        header_title.addMouseListener(frameDragListener);
        header_title.addMouseMotionListener(frameDragListener);
        
        ComponentResizer componentResizer = new ComponentResizer(new Insets(10, 10, 10, 10), this);
        componentResizer.setSnapSize(new Dimension(15, 15));
        
        BackgroundMenuBar menuBar = new BackgroundMenuBar();
        menuBar.setBorder(null);
        menuBar.setColor(new Color(42,42,42));
                
        JMenu menu = new JMenu("Arquivo");
        menu.setForeground(Color.white);
        
        JMenuItem menuItem = new JMenuItem("Novo Universo");
        menu.add(menuItem);
        menuItem = new JMenuItem("Abrir Universo");
        menu.add(menuItem);
        
        menu.add(new JSeparator());
        
        menuItem = new JMenuItem("Salvar");
        menu.add(menuItem);
        menuItem = new JMenuItem("Exportar");
        menu.add(menuItem);
        
        menu.add(new JSeparator());
        
        menuItem = new JMenuItem("Fechar");
        menu.add(menuItem);
        menuBar.add(menu);
        
        menu = new JMenu("Editar");
        menu.setForeground(Color.white);
        menuBar.add(menu);
        
        header_panel.add(menuBar, BorderLayout.PAGE_END);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_panel = new javax.swing.JPanel();
        header_actions_panel = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        minimize_btn = new javax.swing.JButton();
        maximize_btn = new javax.swing.JButton();
        header_title = new javax.swing.JLabel();
        header_padding_panel = new javax.swing.JPanel();
        footer_panel = new javax.swing.JPanel();
        footer_title = new javax.swing.JLabel();
        main_panel = new Src.CustomWidgets.GridPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 42));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 1));

        header_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 42, 42), 5));
        header_panel.setPreferredSize(new java.awt.Dimension(800, 90));
        header_panel.setLayout(new java.awt.BorderLayout(10, 0));

        header_actions_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_actions_panel.setRequestFocusEnabled(false);
        header_actions_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        close_btn.setBackground(new java.awt.Color(0, 0, 0));
        close_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn.png"))); // NOI18N
        close_btn.setToolTipText("");
        close_btn.setBorderPainted(false);
        close_btn.setContentAreaFilled(false);
        close_btn.setFocusPainted(false);
        close_btn.setFocusable(false);
        close_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        close_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        close_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        close_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(close_btn);

        minimize_btn.setBackground(new java.awt.Color(0, 0, 0));
        minimize_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn.png"))); // NOI18N
        minimize_btn.setToolTipText("");
        minimize_btn.setBorderPainted(false);
        minimize_btn.setContentAreaFilled(false);
        minimize_btn.setFocusPainted(false);
        minimize_btn.setFocusable(false);
        minimize_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimize_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        minimize_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        minimize_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        minimize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_btnMouseExited(evt);
            }
        });
        minimize_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(minimize_btn);

        maximize_btn.setBackground(new java.awt.Color(0, 0, 0));
        maximize_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn.png"))); // NOI18N
        maximize_btn.setToolTipText("");
        maximize_btn.setBorderPainted(false);
        maximize_btn.setContentAreaFilled(false);
        maximize_btn.setFocusPainted(false);
        maximize_btn.setFocusable(false);
        maximize_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maximize_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        maximize_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        maximize_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        maximize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximize_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximize_btnMouseExited(evt);
            }
        });
        maximize_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximize_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(maximize_btn);

        header_panel.add(header_actions_panel, java.awt.BorderLayout.LINE_START);

        header_title.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        header_title.setForeground(new java.awt.Color(255, 255, 255));
        header_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_title.setText("IoTVerse Simulator");
        header_title.setToolTipText("");
        header_title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header_panel.add(header_title, java.awt.BorderLayout.CENTER);

        header_padding_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_padding_panel.setPreferredSize(new java.awt.Dimension(110, 65));
        header_padding_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));
        header_panel.add(header_padding_panel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header_panel, java.awt.BorderLayout.PAGE_START);

        footer_panel.setBackground(new java.awt.Color(255, 255, 255));
        footer_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        footer_panel.setPreferredSize(new java.awt.Dimension(800, 40));
        footer_panel.setLayout(new java.awt.BorderLayout(0, 10));

        footer_title.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        footer_title.setForeground(new java.awt.Color(42, 42, 42));
        footer_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_title.setText("V0.0.1 @ CleberPeter");
        footer_title.setToolTipText("");
        footer_title.setRequestFocusEnabled(false);
        footer_panel.add(footer_title, java.awt.BorderLayout.CENTER);

        getContentPane().add(footer_panel, java.awt.BorderLayout.PAGE_END);

        main_panel.setBackground(new java.awt.Color(42, 42, 42));
        main_panel.setcellSize(50);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        getContentPane().add(main_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn_focused.png"))); // NOI18N
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn.png"))); // NOI18N
    }//GEN-LAST:event_close_btnMouseExited

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void minimize_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseEntered
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn_focused.png"))); // NOI18N
    }//GEN-LAST:event_minimize_btnMouseEntered

    private void minimize_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseExited
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn.png"))); // NOI18N
    }//GEN-LAST:event_minimize_btnMouseExited

    private void minimize_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_btnActionPerformed
        setExtendedState(java.awt.Frame.ICONIFIED);
        maximized = false;
    }//GEN-LAST:event_minimize_btnActionPerformed

    private void maximize_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximize_btnMouseEntered
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn_focused.png")));
    }//GEN-LAST:event_maximize_btnMouseEntered

    private void maximize_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximize_btnMouseExited
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn.png"))); 
    }//GEN-LAST:event_maximize_btnMouseExited

    private void maximize_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximize_btnActionPerformed
        
        if (!maximized)
        {
            setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
            maximized = true;
        }
        else
        {
            setExtendedState(java.awt.Frame.NORMAL);
            maximized = false;
        }
    }//GEN-LAST:event_maximize_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private Boolean maximized;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JLabel footer_title;
    private javax.swing.JPanel header_actions_panel;
    private javax.swing.JPanel header_padding_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel header_title;
    private Src.CustomWidgets.GridPanel main_panel;
    private javax.swing.JButton maximize_btn;
    private javax.swing.JButton minimize_btn;
    // End of variables declaration//GEN-END:variables
}
