/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Src;

import Src.CustomWidgets.BackgroundMenuBar;
import Src.CustomWidgets.ComponentResizer;
import Src.CustomWidgets.FrameDragListener;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JSeparator;
import javax.swing.UIManager;

/**
 *
 * @author cleber
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateUniserveFrame
     */
    public MainFrame() {
        initComponents();
        
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        maximized = true;
        
        FrameDragListener frameDragListener = new FrameDragListener(this);
        header_title.addMouseListener(frameDragListener);
        header_title.addMouseMotionListener(frameDragListener);
        
        ComponentResizer componentResizer = new ComponentResizer(new Insets(10, 10, 10, 10), this);
        componentResizer.setSnapSize(new Dimension(15, 15));
        
        menu_bar_file_panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header_panel = new javax.swing.JPanel();
        header_actions_panel = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        minimize_btn = new javax.swing.JButton();
        maximize_btn = new javax.swing.JButton();
        header_title = new javax.swing.JLabel();
        header_padding_panel = new javax.swing.JPanel();
        menu_bar_panel = new javax.swing.JPanel();
        menu_bar_file_btn = new javax.swing.JButton();
        menu_bar_edit_btn = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        menu_bar_file_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        main_panel = new Src.CustomWidgets.GridPanel();
        footer_panel = new javax.swing.JPanel();
        footer_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 42));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 1));

        header_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 42, 42), 5));
        header_panel.setPreferredSize(new java.awt.Dimension(800, 90));
        header_panel.setLayout(new java.awt.BorderLayout(10, 0));

        header_actions_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_actions_panel.setRequestFocusEnabled(false);
        header_actions_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        close_btn.setBackground(new java.awt.Color(0, 0, 0));
        close_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn.png"))); // NOI18N
        close_btn.setToolTipText("");
        close_btn.setBorderPainted(false);
        close_btn.setContentAreaFilled(false);
        close_btn.setFocusPainted(false);
        close_btn.setFocusable(false);
        close_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        close_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        close_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        close_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(close_btn);

        minimize_btn.setBackground(new java.awt.Color(0, 0, 0));
        minimize_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn.png"))); // NOI18N
        minimize_btn.setToolTipText("");
        minimize_btn.setBorderPainted(false);
        minimize_btn.setContentAreaFilled(false);
        minimize_btn.setFocusPainted(false);
        minimize_btn.setFocusable(false);
        minimize_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimize_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        minimize_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        minimize_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        minimize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_btnMouseExited(evt);
            }
        });
        minimize_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(minimize_btn);

        maximize_btn.setBackground(new java.awt.Color(0, 0, 0));
        maximize_btn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn.png"))); // NOI18N
        maximize_btn.setToolTipText("");
        maximize_btn.setBorderPainted(false);
        maximize_btn.setContentAreaFilled(false);
        maximize_btn.setFocusPainted(false);
        maximize_btn.setFocusable(false);
        maximize_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maximize_btn.setMaximumSize(new java.awt.Dimension(25, 25));
        maximize_btn.setMinimumSize(new java.awt.Dimension(25, 25));
        maximize_btn.setPreferredSize(new java.awt.Dimension(30, 25));
        maximize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximize_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximize_btnMouseExited(evt);
            }
        });
        maximize_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximize_btnActionPerformed(evt);
            }
        });
        header_actions_panel.add(maximize_btn);

        header_panel.add(header_actions_panel, java.awt.BorderLayout.LINE_START);

        header_title.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        header_title.setForeground(new java.awt.Color(255, 255, 255));
        header_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_title.setText("IoTVerse Simulator");
        header_title.setToolTipText("");
        header_title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header_panel.add(header_title, java.awt.BorderLayout.CENTER);

        header_padding_panel.setBackground(new java.awt.Color(42, 42, 42));
        header_padding_panel.setPreferredSize(new java.awt.Dimension(110, 65));
        header_padding_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));
        header_panel.add(header_padding_panel, java.awt.BorderLayout.LINE_END);

        menu_bar_panel.setBackground(new java.awt.Color(42, 42, 42));
        menu_bar_panel.setPreferredSize(new java.awt.Dimension(1032, 30));
        menu_bar_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        menu_bar_file_btn.setBackground(new java.awt.Color(42, 42, 42));
        menu_bar_file_btn.setForeground(new java.awt.Color(255, 255, 255));
        menu_bar_file_btn.setText("Arquivo");
        menu_bar_file_btn.setContentAreaFilled(false);
        menu_bar_file_btn.setPreferredSize(new java.awt.Dimension(74, 27));
        menu_bar_file_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bar_file_btnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_bar_file_btnMouseExited(evt);
            }
        });
        menu_bar_file_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bar_file_btnActionPerformed(evt);
            }
        });
        menu_bar_panel.add(menu_bar_file_btn);

        menu_bar_edit_btn.setBackground(new java.awt.Color(42, 42, 42));
        menu_bar_edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        menu_bar_edit_btn.setText("Editar");
        menu_bar_edit_btn.setContentAreaFilled(false);
        menu_bar_edit_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_bar_edit_btn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        menu_bar_edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bar_edit_btnActionPerformed(evt);
            }
        });
        menu_bar_panel.add(menu_bar_edit_btn);

        header_panel.add(menu_bar_panel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(header_panel, java.awt.BorderLayout.PAGE_START);

        java.awt.GridBagLayout jLayeredPane1Layout = new java.awt.GridBagLayout();
        jLayeredPane1Layout.columnWeights = new double[] {0.5};
        jLayeredPane1Layout.rowWeights = new double[] {0.5};
        jLayeredPane1.setLayout(jLayeredPane1Layout);

        menu_bar_file_panel.setBackground(new java.awt.Color(40, 40, 40));
        menu_bar_file_panel.setPreferredSize(new java.awt.Dimension(243, 100));
        menu_bar_file_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_bar_file_panelMouseExited(evt);
            }
        });
        java.awt.GridBagLayout menu_bar_file_panelLayout = new java.awt.GridBagLayout();
        menu_bar_file_panelLayout.columnWeights = new double[] {0.5};
        menu_bar_file_panelLayout.rowWeights = new double[] {0.5};
        menu_bar_file_panel.setLayout(menu_bar_file_panelLayout);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        menu_bar_file_panel.add(jSeparator1, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salvar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        menu_bar_file_panel.add(jLabel3, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Exportar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        menu_bar_file_panel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        menu_bar_file_panel.add(jSeparator2, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sair");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        menu_bar_file_panel.add(jLabel5, gridBagConstraints);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new_file_white.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(8);
        jButton1.setMargin(new java.awt.Insets(0, -10, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        menu_bar_file_panel.add(jButton1, gridBagConstraints);

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open_file_white.png"))); // NOI18N
        jButton2.setText("Abrir");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(6);
        jButton2.setMargin(new java.awt.Insets(0, -10, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        menu_bar_file_panel.add(jButton2, gridBagConstraints);

        jLayeredPane1.setLayer(menu_bar_file_panel, javax.swing.JLayeredPane.MODAL_LAYER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jLayeredPane1.add(menu_bar_file_panel, gridBagConstraints);

        main_panel.setBackground(new java.awt.Color(42, 42, 42));
        main_panel.setcellSize(50);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1520, Short.MAX_VALUE)
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1054;
        gridBagConstraints.ipady = 392;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jLayeredPane1.add(main_panel, gridBagConstraints);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        footer_panel.setBackground(new java.awt.Color(255, 255, 255));
        footer_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        footer_panel.setPreferredSize(new java.awt.Dimension(800, 40));
        footer_panel.setLayout(new java.awt.BorderLayout(0, 10));

        footer_title.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        footer_title.setForeground(new java.awt.Color(42, 42, 42));
        footer_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_title.setText("V0.0.1 @ CleberPeter");
        footer_title.setToolTipText("");
        footer_title.setRequestFocusEnabled(false);
        footer_panel.add(footer_title, java.awt.BorderLayout.CENTER);

        getContentPane().add(footer_panel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn_focused.png"))); // NOI18N
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_btn.png"))); // NOI18N
    }//GEN-LAST:event_close_btnMouseExited

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void minimize_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseEntered
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn_focused.png"))); // NOI18N
    }//GEN-LAST:event_minimize_btnMouseEntered

    private void minimize_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseExited
        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_btn.png"))); // NOI18N
    }//GEN-LAST:event_minimize_btnMouseExited

    private void minimize_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_btnActionPerformed
        setExtendedState(java.awt.Frame.ICONIFIED);
        maximized = false;
    }//GEN-LAST:event_minimize_btnActionPerformed

    private void maximize_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximize_btnMouseEntered
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn_focused.png")));
    }//GEN-LAST:event_maximize_btnMouseEntered

    private void maximize_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximize_btnMouseExited
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maximize_btn.png"))); 
    }//GEN-LAST:event_maximize_btnMouseExited

    private void maximize_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximize_btnActionPerformed
        
        if (!maximized)
        {
            setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
            maximized = true;
        }
        else
        {
            setExtendedState(java.awt.Frame.NORMAL);
            maximized = false;
        }
    }//GEN-LAST:event_maximize_btnActionPerformed

    private void menu_bar_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bar_file_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_bar_file_btnActionPerformed

    private void menu_bar_edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bar_edit_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_bar_edit_btnActionPerformed

    private void menu_bar_file_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bar_file_btnMouseClicked
        menu_bar_file_panel.setVisible(true);
    }//GEN-LAST:event_menu_bar_file_btnMouseClicked

    private void menu_bar_file_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bar_file_btnMouseExited
        
    }//GEN-LAST:event_menu_bar_file_btnMouseExited

    private void menu_bar_file_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bar_file_panelMouseExited
        menu_bar_file_panel.setVisible(false);
    }//GEN-LAST:event_menu_bar_file_panelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private Boolean maximized;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JLabel footer_title;
    private javax.swing.JPanel header_actions_panel;
    private javax.swing.JPanel header_padding_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel header_title;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private Src.CustomWidgets.GridPanel main_panel;
    private javax.swing.JButton maximize_btn;
    private javax.swing.JButton menu_bar_edit_btn;
    private javax.swing.JButton menu_bar_file_btn;
    private javax.swing.JPanel menu_bar_file_panel;
    private javax.swing.JPanel menu_bar_panel;
    private javax.swing.JButton minimize_btn;
    // End of variables declaration//GEN-END:variables
}
